### ISSUE TITLE
I Follow the instruction Correctly But this happens

### ISSUE THREAD

**Issue by sarifulshikder** [kevindoni/interfacemonitoring#1]
![image](https://github.com/kevindoni/interfacemonitoring/assets/90824320/a7ab3cd1-05e5-46b5-8652-bf9ae53bc4fa)

**Comment by kevindoni** [comment]
OK, I'll fix it, it seems to conflict with the others

**Comment by kevindoni** [comment]
> ![image](https://private-user-images.githubusercontent.com/90824320/340912680-a7ab3cd1-05e5-46b5-8652-bf9ae53bc4fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMjYwMDAsIm5iZiI6MTcxOTIyNTcwMCwicGF0aCI6Ii85MDgyNDMyMC8zNDA5MTI2ODAtYTdhYjNjZDEtMDVlNS00NmI1LTg2NTItYmY5YWU1M2JjNGZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDEwNDE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhOGU5NDI2ZDBhMGQ3MGJlMDliMGJjZmQwMDM1YTU1MGFhYmQxYzQ2MDE4ZjYxNDEzMmJkMGYzMjAzMTQ1YjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N8krHWc9Gu92XMc-eVyW3Ozcs5VDcNIMlDbFI14hug0)

Please try, I've fixed it

Update Interface Functions That Conflict with Other Interface Functions
